openapi: "3.0.0"
info:
  version: 1.0.0
  title: Kids Keeper API Docs
  description: Kids Keeper API 문서
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: dev servers
    url: http://localhost:3000/api/
paths:
  $ref: "./paths/index.yaml"
tags:
  - name: district
  - name: children care center
