name: Lint Action - PY(ML)

on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: models

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Python Lint
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Model dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Lint with black
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: ${{ github.event_name == 'pull_request' }}
          black: true

      - name: Lint with flake8
        run: |
          pip install flake8 isort black
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
